# NumPy Day 2 — Code Lab

**Beginner → ML Foundation**

Topics: Aggregation, Axis, Reshape, Flatten, Transpose, Boolean Masking, Array Creation, Random Numbers, Broadcasting, Matrix Operations, and a Mini ML Dataset.

## Part 1 — Aggregation Functions

In [2]:
import numpy as np

marks = np.array([70, 80, 65, 90, 75])

# Task 1: Find the total marks
# Write your code here

print(np.sum(marks))


380


In [3]:
# Task 2: Find the average marks
# Write your code here
print(np.mean(marks))

76.0


In [4]:
# Task 3: Find the minimum and maximum marks
# Write your code here
print(np.min(marks))
print(np.max(marks))

65
90


In [5]:
# Task 4: Find the standard deviation
# Write your code here
print(np.std(marks))

8.602325267042627


## Part 2 — Axis

In [7]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Task 5: Find the sum of each column
# Hint: axis=0
# Write your code here
print(data.shape)
print(np.sum(data,axis=0))

(3, 3)
[120 150 180]


In [8]:
# Task 6: Find the sum of each row
# Hint: axis=1
# Write your code here
print(np.sum(data,axis=1))

[ 60 150 240]


## Part 3 — Reshaping

In [9]:
# Task 7: Convert the 1D array into a 2 x 3 array

arr = np.array([1, 2, 3, 4, 5, 6])

# Write your code here

arr2 = arr.reshape(2,3)
print(arr2)


[[1 2 3]
 [4 5 6]]


In [10]:
# Task 8: Convert the array into a 3 x 2 array

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Write your code here
arr2 = arr.reshape(3,2)
print(arr2)


[[1 2]
 [3 4]
 [5 6]]


## Part 4 — Flattening

In [11]:
# Task 9: Convert this 2D array into 1D using flatten()

data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Write your code here
print(data.flatten())


[1 2 3 4 5 6]


## Part 5 — Transpose

In [12]:
# Task 10: Transpose the array using .T

data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Write your code here

print(data.T)


[[1 4]
 [2 5]
 [3 6]]


## Part 6 — Boolean Masking

In [13]:
marks = np.array([45, 78, 90, 32, 88, 65])

# Task 11: Print marks greater than 70
# Write your code here
print(marks > 80)

[False False  True False  True False]


In [14]:
# Task 12: Print marks less than 50
# Write your code here
print(marks < 50)

[ True False False  True False False]


In [15]:
# Task 13: Print marks between 50 and 80
# Hint: use (marks >= 50) & (marks <= 80)
# Write your code here
marks[(marks >= 50) & (marks <= 80)]

array([78, 65])

## Part 7 — Array Creation

In [16]:
# Task 14: Create an array of five zeros
# Write your code here
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
# Task 15: Create an array of five ones
# Write your code here
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [19]:
# Task 16: Create numbers from 1 to 20 using np.arange()
# Write your code here
np.arange(0,20,2) #np.arange(start, stop, step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# Task 17: Create 5 equally spaced numbers between 0 and 1 using np.linspace()
# Write your code here

np.linspace(0,1,5) #np.linspace(start, stop, number_of_values)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Part 8 — Random Numbers

In [21]:
# Task 18: Generate 10 random integers between 1 and 100
# Write your code here
np.random.randint(1,100,10)

array([21, 21, 94, 94, 61, 84,  4, 17, 21, 81], dtype=int32)

In [ ]:
# Task 19: Generate 5 random decimal numbers between 0 and 1
# Write your code here
np.random.rand(5) #rand() automatically uses the range 0 ≤ number < 1.

array([0.44762458, 0.67423064, 0.94906518, 0.7554963 , 0.06774894])

## Part 9 — Broadcasting

In [24]:
# Task 20: Add 5 to every mark

marks = np.array([60, 70, 80, 90])

# Write your code here

print(marks + 5)


[65 75 85 95]


In [25]:
arr =[10,20,30.40]
arr2 =[]

for i in arr:
    print(i +5)

15
25
35.4


In [26]:
# Task 21: Apply a 10% bonus to every mark
marks = np.array([60, 70, 80, 90])

# Hint: marks * 1.10
# Write your code here
bonus = marks * 1.10
print(marks+bonus)

[126. 147. 168. 189.]


## Part 10 — Matrix Operations

In [28]:
A = np.array([[1, 2 ], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Task 22: Find A+B, A-B, and A*B
# Write your code here
print(A+B)
print(A-B)
print(A*B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [29]:
# Task 23: Matrix multiplication
# Calculate A @ B
# Write your code here
print(A@B)

[[19 22]
 [43 50]]


## Part 11 — Mini ML Dataset

Columns: **Age | Study Hours | Marks**

In [30]:
students = np.array([
    [20, 5, 80],
    [21, 6, 75],
    [22, 8, 90],
    [23, 4, 65],
    [24, 7, 85]
])

students


array([[20,  5, 80],
       [21,  6, 75],
       [22,  8, 90],
       [23,  4, 65],
       [24,  7, 85]])

In [32]:
# Task 24: Find the number of students
# Write your code here
print(students.shape[0])

5


In [33]:
# Task 25: Find the average marks
# Write your code here
print(np.mean(students[:,2]))

79.0


In [34]:
# Task 26: Extract the Study Hours column
# Write your code here
print(students[:,1])

[5 6 8 4 7]


In [35]:
# Task 27: Find students who scored more than 80
# Write your code here
print(students[students[:, 2] > 80])

[[22  8 90]
 [24  7 85]]


In [36]:
# Task 28: Find the maximum study hours
# Write your code here
print(np.max(students[:,1]))

8


In [39]:
# Task 29: Find the average of each column
# Write your code here
print(np.mean(students, axis=0))

[22.  6. 79.]


In [40]:
# Task 30: Transpose the dataset
# Write your code here
print(students.T)

[[20 21 22 23 24]
 [ 5  6  8  4  7]
 [80 75 90 65 85]]


# Final Challenge

Solve without looking at previous examples:

1. Find number of students.
2. Find number of features.
3. Calculate average marks.
4. Find highest marks.
5. Find students with marks >= 80.
6. Calculate average study hours.
7. Find the student with highest study hours.
8. Add 5 bonus marks to every student.
9. Reshape the dataset into another valid shape, if possible.
10. Transpose the dataset.

In [ ]:
# Final Challenge

students = np.array([
    [20, 5, 80],
    [21, 6, 75],
    [22, 8, 90],
    [23, 4, 65],
    [24, 7, 85]
])

# Solve all 10 tasks here.
#1.
print(students.shape[0])

5


In [43]:
#2.
print(students.shape[1])

3


In [44]:
#3.
print(np.mean(students[:,2]))

79.0


In [46]:
#4.
print(np.max(students[:,2]))

90


In [51]:
#5.
print(students[:,2]>80)
print(students)

[False False  True False  True]
[[20  5 80]
 [21  6 75]
 [22  8 90]
 [23  4 65]
 [24  7 85]]


In [52]:
#6.
print(np.mean(students[:,1]))

6.0


In [61]:
#7.
high_mark = np.max(students[:,1])
print(students[students[:,1] == high_mark])

[[22  8 90]]


In [62]:
#8.
bonus = students[:,2] + 5
print(bonus)

[85 80 95 70 90]


In [64]:
#9.
print(students.reshape(3,5))

[[20  5 80 21  6]
 [75 22  8 90 23]
 [ 4 65 24  7 85]]


In [65]:
#10.
print(students.T)

[[20 21 22 23 24]
 [ 5  6  8  4  7]
 [80 75 90 65 85]]
